#!/usr/bin/env bash
set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
generated_dir="$script_dir/generated"
provenance_file="$script_dir/PROVENANCE"

for tool in ffmpeg ffprobe sha256sum; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "missing required local tool: $tool" >&2
        exit 1
    }
done

ffmpeg_version=$(ffmpeg -version | head -n 1)
ffprobe_version=$(ffprobe -version | head -n 1)
sha256sum_version=$(sha256sum --version | head -n 1)

rm -rf "$generated_dir"
mkdir -p "$generated_dir/hls-vod" "$generated_dir/hls-live"

common_video=(
    -c:v libx264
    -preset medium
    -crf 23
    -threads 1
    -x264-params keyint=30:min-keyint=30:scenecut=0:threads=1
    -pix_fmt yuv420p
)
common_audio=(
    -c:a aac
    -profile:a aac_low
    -b:a 128k
    -ar 48000
    -ac 2
)
common_output=(
    -map_metadata -1
    -fflags +bitexact
    -flags:v +bitexact
    -flags:a +bitexact
)

ffmpeg -hide_banner -loglevel error \
    -f lavfi -i 'testsrc2=size=320x180:rate=30:duration=2' \
    -f lavfi -i 'sine=frequency=440:sample_rate=48000:duration=2' \
    -map 0:v:0 -map 1:a:0 -t 2 \
    "${common_video[@]}" "${common_audio[@]}" "${common_output[@]}" \
    -movflags +faststart -video_track_timescale 90000 \
    "$generated_dir/h264-aac.mp4"

ffmpeg -hide_banner -loglevel error \
    -f lavfi -i 'testsrc2=size=320x180:rate=30:duration=2' \
    -f lavfi -i 'sine=frequency=550:sample_rate=48000:duration=2' \
    -map 0:v:0 -map 1:a:0 -t 2 \
    -c:v libvpx-vp9 -crf 32 -b:v 0 -deadline good -cpu-used 0 -row-mt 0 -threads 1 \
    -pix_fmt yuv420p -c:a libopus -b:a 96k -ar 48000 -ac 2 \
    "${common_output[@]}" \
    "$generated_dir/vp9-opus.mkv"

ffmpeg -hide_banner -loglevel error \
    -f lavfi -i 'testsrc2=size=320x180:rate=30:duration=2' \
    -f lavfi -i 'sine=frequency=440:sample_rate=48000:duration=2' \
    -f lavfi -i 'sine=frequency=660:sample_rate=48000:duration=2' \
    -map 0:v:0 -map 1:a:0 -map 2:a:0 -t 2 \
    "${common_video[@]}" \
    -c:a:0 aac -profile:a:0 aac_low -b:a:0 128k \
    -c:a:1 aac -profile:a:1 aac_low -b:a:1 128k \
    -ar 48000 -ac 2 \
    -metadata:s:a:0 language=eng -metadata:s:a:0 title='primary' \
    -metadata:s:a:1 language=spa -metadata:s:a:1 title='alternate' \
    -disposition:a:0 default -disposition:a:1 0 \
    "${common_output[@]}" \
    "$generated_dir/dual-aac.mkv"

generate_hls() {
    local playlist_type=$1
    local output_dir=$2
    local duration=${3:-2}

    ffmpeg -hide_banner -loglevel error \
        -f lavfi -i "testsrc2=size=320x180:rate=30:duration=$duration" \
        -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=$duration" \
        -map 0:v:0 -map 1:a:0 -t "$duration" \
        "${common_video[@]}" "${common_audio[@]}" "${common_output[@]}" \
        -force_key_frames 'expr:gte(t,n_forced*1)' \
        -f hls -hls_time 1 -hls_playlist_type "$playlist_type" \
        -hls_flags independent_segments \
        -hls_segment_filename "$output_dir/segment-%03d.ts" \
        "$output_dir/index.m3u8"

    if [[ "$playlist_type" == event ]]; then
        # EVENT is a finite local snapshot for deterministic tests, not a live
        # network source. Keep its playlist open so it has no ENDLIST marker.
        local without_endlist="$output_dir/index.m3u8.tmp"
        grep -v '^#EXT-X-ENDLIST$' "$output_dir/index.m3u8" > "$without_endlist"
        mv "$without_endlist" "$output_dir/index.m3u8"
    fi
}

generate_hls vod "$generated_dir/hls-vod"
# Keep enough sequential media to let the loopback server advance a sliding
# window after a controlled outage and recovery.
generate_hls event "$generated_dir/hls-live" 12

{
    echo "# Generated by fixtures/generate.sh; no network access is required."
    echo "ffmpeg: $ffmpeg_version"
    echo "ffprobe: $ffprobe_version"
    echo "sha256sum: $sha256sum_version"
    echo
    echo "## Media stream probes"
    for media in h264-aac.mp4 vp9-opus.mkv dual-aac.mkv; do
        echo "$media:"
        ffprobe -v error -show_entries stream=index,codec_type,codec_name,width,height,channels \
            -of compact=p=0:nk=1 "$generated_dir/$media" | sed 's/^/  /'
    done
    for playlist in hls-vod/index.m3u8 hls-live/index.m3u8; do
        echo "$playlist:"
        ffprobe -v error -show_entries stream=index,codec_type,codec_name,width,height,channels \
            -of compact=p=0:nk=1 "$generated_dir/$playlist" | sed 's/^/  /'
    done
    echo
    echo "## SHA256 (all generated files)"
    (
        cd "$script_dir"
        find generated -type f -print0 | sort -z | while IFS= read -r -d '' file; do
            sha256sum "$file"
        done
    )
} > "$provenance_file"

echo "generated fixtures under $generated_dir"
echo "recorded tool versions and hashes in $provenance_file"
