/**
 * ExoPlayer Bridge for lumina-video zero-copy video rendering.
 *
 * This class bridges ExoPlayer's video output to lumina-video's Rust rendering pipeline
 * using Android's HardwareBuffer API for zero-copy GPU frame sharing.
 *
 * # Usage
 *
 * Created internally by [LuminaVideo.createPlayer]. Do not construct directly.
 *
 * # Requirements
 *
 * - Android API 26+ (HardwareBuffer)
 * - ExoPlayer 2.x or Media3
 * - lumina-video native library loaded
 *
 * # Frame Format
 *
 * Uses [ImageFormat.PRIVATE] for HardwareBuffer extraction. ExoPlayer's decoder
 * typically produces YUV data (NV12/Y8Cb8Cr8_420). The Rust side handles both:
 * - RGBA buffers: direct single-plane Vulkan import
 * - YUV buffers: true zero-copy via VkSamplerYcbcrConversion, with CPU-assisted
 *   lockPlanes fallback when the Vulkan YUV path is unavailable
 */
package com.luminavideo.bridge

import android.content.Context
import android.graphics.ImageFormat
import android.hardware.HardwareBuffer
import android.media.ImageReader
import android.os.Handler
import android.os.HandlerThread
import android.util.Log
import android.view.Surface
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.common.Player
import androidx.media3.common.VideoSize
import androidx.media3.exoplayer.ExoPlayer
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger

/**
 * Bridge between ExoPlayer and lumina-video's Rust zero-copy rendering.
 *
 * Extracts HardwareBuffer from decoded video frames via ImageReader
 * and submits them to Rust via JNI for GPU-accelerated display.
 *
 * Instances are created by [LuminaVideo.createPlayer] — do not construct directly.
 */
class ExoPlayerBridge internal constructor(private val nativeHandle: Long = 0L) {

    companion object {
        private const val TAG = "ExoPlayerBridge"

        /** Maximum number of images to hold in the ImageReader buffer */
        // Covers the displayed frame, bounded scheduler queue, and Vulkan's
        // four-frame conversion ring without returning an in-use slot early.
        private const val MAX_IMAGES = 8

        /** Timeout for ExoPlayer creation on the HandlerThread */
        private const val INIT_TIMEOUT_SECONDS = 5L

        /** Whether the native library was successfully loaded */
        private var nativeLibraryLoaded = false

        init {
            try {
                System.loadLibrary("lumina_video_android")
                nativeLibraryLoaded = true
                Log.i(TAG, "Loaded liblumina_video_android.so")
            } catch (e: UnsatisfiedLinkError) {
                // Embedders such as GPUI Mobile load the Rust cdylib through
                // NativeActivity under the application's library name. JNI
                // entry points are already resident in that case.
                nativeLibraryLoaded = true
                Log.i(TAG, "Using native library loaded by the host application")
            }
        }
    }

    // ImageReader for capturing decoded frames
    private var imageReader: ImageReader? = null

    // Surface provided to ExoPlayer for rendering
    private var surface: Surface? = null

    // Dedicated Looper thread for ExoPlayer (ExoPlayer requires a Looper thread)
    private var handlerThread: HandlerThread? = null
    private var handler: Handler? = null

    // Volume before muting (to restore on unmute)
    private var volumeBeforeMute: Float = 1.0f

    // Player reference for lifecycle management
    private var player: ExoPlayer? = null

    // State tracking
    private val isReleased = AtomicBoolean(false)
    private val frameCount = AtomicInteger(0)

    // Player listener for cleanup on release
    private var playerListener: Player.Listener? = null

    // Player ID for per-player frame queue routing.
    // Generated by nativeGeneratePlayerId() during init; 0 = not yet assigned.
    private var playerId: Long = 0L

    // Current video dimensions (updated on video size change)
    private var videoWidth = 0
    private var videoHeight = 0

    // True when Surface is provided by native NDK ImageReader (via setVideoSurfaceFromNative)
    private var ndkMode = false

    // Cached position/duration — updated on player thread, read from any thread.
    // ExoPlayer with setLooper() enforces thread access, so we can't call getters directly
    // from Rust's decode thread. These volatile fields provide stale-but-safe reads.
    @Volatile private var cachedPositionMs: Long = 0L
    @Volatile private var cachedDurationMs: Long = -1L

    // ImageReader timestamps use Android's monotonic clock rather than the
    // media timeline. Their deltas are nevertheless the decoder's precise
    // presentation cadence, so anchor those deltas to ExoPlayer position.
    private var frameClockImageAnchorNs: Long = Long.MIN_VALUE
    private var frameClockMediaAnchorNs: Long = 0L
    private var lastFrameMediaTimestampNs: Long = Long.MIN_VALUE
    private var currentSourceIsHls: Boolean = false
    private var livePositionOffsetMs: Long = 0L
    private var lastLivePositionMs: Long = Long.MIN_VALUE

    private fun resetFrameClock() {
        frameClockImageAnchorNs = Long.MIN_VALUE
        frameClockMediaAnchorNs = 0L
        lastFrameMediaTimestampNs = Long.MIN_VALUE
    }

    private fun resetLivePositionClock() {
        livePositionOffsetMs = 0L
        lastLivePositionMs = Long.MIN_VALUE
    }

    /**
     * ExoPlayer reports a position relative to the current HLS live window.
     * When that window slides at a segment boundary, the raw position can move
     * backwards (for example 3s -> 2s). Convert it to one monotonic playback
     * timeline shared by frame PTS, the native audio clock, and the UI.
     */
    private fun normalizedPositionMs(rawPositionMs: Long): Long {
        val raw = rawPositionMs.coerceAtLeast(0L)
        if (!currentSourceIsHls) {
            return raw
        }

        var normalized = raw + livePositionOffsetMs
        if (lastLivePositionMs != Long.MIN_VALUE && normalized < lastLivePositionMs) {
            livePositionOffsetMs += lastLivePositionMs - normalized
            normalized = lastLivePositionMs
        }
        lastLivePositionMs = normalized
        return normalized
    }

    private fun mediaTimestampForImage(imageTimestampNs: Long, mediaPositionMs: Long): Long {
        val currentMediaNs = mediaPositionMs.coerceAtLeast(0L) * 1_000_000L

        // MediaCodec/ImageReader timestamps can jump at HLS segment boundaries.
        // ExoPlayer's position is already the authoritative media/audio clock,
        // so map live HLS frames directly onto it instead of interpreting a
        // segment timestamp jump as a gap in the presentation timeline.
        if (currentSourceIsHls) {
            val mappedMediaNs = if (lastFrameMediaTimestampNs == Long.MIN_VALUE) {
                currentMediaNs
            } else {
                // Multiple ImageReader callbacks may observe the same
                // millisecond-resolution ExoPlayer position. Preserve ordering
                // without manufacturing a visible lead over the master clock.
                maxOf(currentMediaNs, lastFrameMediaTimestampNs + 1_000_000L)
            }
            lastFrameMediaTimestampNs = mappedMediaNs
            return mappedMediaNs
        }

        if (frameClockImageAnchorNs == Long.MIN_VALUE) {
            frameClockImageAnchorNs = imageTimestampNs
            frameClockMediaAnchorNs = currentMediaNs
            lastFrameMediaTimestampNs = currentMediaNs
            return currentMediaNs
        }

        val imageDeltaNs = (imageTimestampNs - frameClockImageAnchorNs).coerceAtLeast(0L)
        var predictedMediaNs = frameClockMediaAnchorNs + imageDeltaNs

        // Pauses, seeks, decoder flushes, and surface recreation break the
        // monotonic-to-media mapping. Re-anchor instead of allowing drift.
        val driftNs = kotlin.math.abs(predictedMediaNs - currentMediaNs)
        // ImageReader/MediaCodec can expose frames roughly 150-200ms ahead of
        // ExoPlayer's audio clock. With a bounded two-frame queue that offset
        // never drains and every frame misses the scheduler's 33ms window.
        // Re-anchor once drift exceeds roughly one 24/30fps frame.
        if (driftNs > 40_000_000L ||
            predictedMediaNs < lastFrameMediaTimestampNs
        ) {
            frameClockImageAnchorNs = imageTimestampNs
            frameClockMediaAnchorNs = currentMediaNs
            predictedMediaNs = currentMediaNs
        }

        lastFrameMediaTimestampNs = predictedMediaNs
        return predictedMediaNs
    }

    /**
     * Creates ExoPlayer on a dedicated HandlerThread and sets up ImageReader.
     *
     * This method blocks the calling thread (via CountDownLatch) until ExoPlayer
     * is fully initialized, or until [INIT_TIMEOUT_SECONDS] elapses.
     *
     * Called by [LuminaVideo.createPlayer] from a Rust background thread.
     *
     * @param context Application context for ExoPlayer creation
     * @param builder Optional custom ExoPlayer.Builder. If null, default is used.
     * @return true if ExoPlayer was created successfully, false on timeout or error
     */
    internal fun initializeWithPlayer(context: Context, builder: ExoPlayer.Builder? = null): Boolean {
        if (isReleased.get()) {
            Log.w(TAG, "Cannot initialize - bridge is released")
            return false
        }

        if (!nativeLibraryLoaded) {
            Log.e(TAG, "Cannot initialize - native library not loaded")
            return false
        }

        // Generate unique player ID for per-player frame queue isolation
        playerId = try {
            nativeGeneratePlayerId()
        } catch (e: Exception) {
            Log.e(TAG, "nativeGeneratePlayerId() failed, using legacy queue: ${e.message}")
            0L
        }
        Log.i(TAG, "Assigned player_id=$playerId")

        // Create dedicated Looper thread for this player instance
        handlerThread = HandlerThread("LuminaVideoPlayer").apply { start() }
        handler = Handler(handlerThread!!.looper)

        val latch = CountDownLatch(1)
        var success = false

        handler!!.post {
            try {
                val exoPlayer = (builder ?: ExoPlayer.Builder(context))
                    .setLooper(handlerThread!!.looper)
                    .build()
                    .apply {
                        setVideoScalingMode(androidx.media3.common.C.VIDEO_SCALING_MODE_SCALE_TO_FIT)
                    }

                player = exoPlayer
                setupListenersAndSurface(exoPlayer)
                success = true
                Log.i(TAG, "ExoPlayer created on ${Thread.currentThread().name}")
            } catch (e: Exception) {
                Log.e(TAG, "Failed to create ExoPlayer: ${e.message}", e)
            }
            latch.countDown()
        }

        val completed = latch.await(INIT_TIMEOUT_SECONDS, TimeUnit.SECONDS)
        if (!completed || !success) {
            Log.e(TAG, "ExoPlayer creation ${if (!completed) "timed out" else "failed"} after ${INIT_TIMEOUT_SECONDS}s, cleaning up")
            release()
            return false
        }

        return true
    }

    /**
     * Sets up video size listener and initial ImageReader surface on the player.
     *
     * Must be called on the player's Looper thread.
     */
    private fun setupListenersAndSurface(exoPlayer: ExoPlayer) {
        // Listen for video size changes, playback state, and errors
        playerListener = object : Player.Listener {
            override fun onVideoSizeChanged(videoSize: VideoSize) {
                Log.d(TAG, "onVideoSizeChanged: ${videoSize.width}x${videoSize.height}")
                if (videoSize.width > 0 && videoSize.height > 0) {
                    // Don't set videoWidth/videoHeight here — setupImageReader checks
                    // them for its early-return guard and updates them itself
                    if (!ndkMode) {
                        setupImageReader(videoSize.width, videoSize.height)
                    }
                    if (nativeHandle != 0L) {
                        nativeOnVideoSizeChanged(nativeHandle, videoSize.width, videoSize.height)
                    }
                }
            }

            override fun onPlaybackStateChanged(playbackState: Int) {
                updateCachedValues()
                if (nativeHandle != 0L) {
                    nativeOnPlaybackStateChanged(nativeHandle, playbackState)
                }
            }

            override fun onIsPlayingChanged(isPlaying: Boolean) {
                updateCachedValues()
                if (nativeHandle != 0L) {
                    val dur = exoPlayer.duration
                    val durationMs =
                        if (currentSourceIsHls || dur == androidx.media3.common.C.TIME_UNSET) {
                            -1L
                        } else {
                            dur
                        }
                    nativeOnDurationChanged(nativeHandle, durationMs)
                }
            }

            override fun onPositionDiscontinuity(
                oldPosition: Player.PositionInfo,
                newPosition: Player.PositionInfo,
                reason: Int
            ) {
                resetFrameClock()
                cachedPositionMs = normalizedPositionMs(newPosition.positionMs)
            }

            override fun onPlayerError(error: androidx.media3.common.PlaybackException) {
                Log.e(TAG, "ExoPlayer error: ${error.message}", error)
                if (nativeHandle != 0L) {
                    nativeOnError(nativeHandle, error.message ?: "Unknown ExoPlayer error")
                }
            }
        }
        exoPlayer.addListener(playerListener!!)

        // Periodically update cached position/duration on the player thread
        // so Rust can read them from any thread via volatile fields
        startPositionUpdater()

        // Create initial ImageReader (unless NDK mode is active)
        if (!ndkMode && imageReader == null && surface == null) {
            Log.i(TAG, "Creating initial ImageReader with default 1920x1080 size")
            setupImageReader(1920, 1080)
        }
    }

    /**
     * Loads and plays a video from the given URL.
     *
     * Called by Rust code to start video playback. Posts to the player's
     * HandlerThread to satisfy ExoPlayer's threading requirements.
     */
    fun play(url: String) {
        handler?.post {
            val p = player
            if (p == null) {
                Log.w(TAG, "play() called but player not initialized")
                return@post
            }
            Log.d(TAG, "play($url)")
            try {
                currentSourceIsHls =
                    url.contains("/hls/", ignoreCase = true) ||
                    url.contains(".m3u8", ignoreCase = true)
                resetFrameClock()
                resetLivePositionClock()
                val mediaItem = MediaItem.Builder()
                    .setUri(url)
                    .apply {
                        if (currentSourceIsHls) {
                            setMimeType(MimeTypes.APPLICATION_M3U8)
                        }
                    }
                    .build()
                p.setMediaItem(mediaItem)
                p.prepare()
                p.play()
            } catch (error: Exception) {
                Log.e(TAG, "Failed to start playback for $url: ${error.message}", error)
                if (nativeHandle != 0L) {
                    nativeOnError(
                        nativeHandle,
                        error.message ?: "Failed to configure ExoPlayer media source"
                    )
                }
            }
        } ?: Log.w(TAG, "play() called before initializeWithPlayer()")
    }

    /**
     * Pauses video playback.
     */
    fun pause() {
        handler?.post { player?.pause() }
    }

    /**
     * Resumes video playback.
     */
    fun resume() {
        handler?.post { player?.play() }
    }

    /**
     * Seeks to the specified position.
     *
     * @param positionMs Position in milliseconds
     */
    fun seek(positionMs: Long) {
        handler?.post {
            resetFrameClock()
            resetLivePositionClock()
            player?.seekTo(positionMs)
        }
    }

    /**
     * Sets the playback volume.
     *
     * @param volume Volume level (0.0 to 1.0)
     */
    fun setVolume(volume: Float) {
        handler?.post { player?.let { it.volume = volume.coerceIn(0f, 1f) } }
    }

    /**
     * Sets the muted state.
     *
     * @param muted True to mute, false to unmute
     */
    fun setMuted(muted: Boolean) {
        handler?.post {
            player?.let { p ->
                if (muted) {
                    volumeBeforeMute = p.volume
                    p.volume = 0f
                } else {
                    p.volume = volumeBeforeMute
                }
            }
        }
    }

    /**
     * Updates cached position/duration from the player.
     * Must be called on the player's Looper thread.
     */
    private fun updateCachedValues() {
        player?.let { p ->
            cachedPositionMs = normalizedPositionMs(p.currentPosition)
            val dur = p.duration
            cachedDurationMs =
                if (currentSourceIsHls || dur == androidx.media3.common.C.TIME_UNSET) {
                    -1L
                } else {
                    dur
                }
        }
    }

    /**
     * Starts a periodic Runnable on the handler thread to update cached position.
     * Runs every 250ms while the player is alive.
     */
    private fun startPositionUpdater() {
        val updater = object : Runnable {
            override fun run() {
                if (!isReleased.get()) {
                    updateCachedValues()
                    handler?.postDelayed(this, 250)
                }
            }
        }
        handler?.postDelayed(updater, 250)
    }

    /**
     * Gets the current playback position in milliseconds.
     *
     * Returns a cached value updated every ~250ms on the player thread.
     * Safe to call from any thread (Rust decode thread, main thread, etc.).
     *
     * @return Current position in ms, or 0 if not playing
     */
    fun getCurrentPosition(): Long {
        return cachedPositionMs
    }

    /**
     * Gets the total duration of the video in milliseconds.
     *
     * Returns a cached value updated on playback state changes and periodically.
     * Safe to call from any thread.
     *
     * @return Duration in ms, or -1 if unknown
     */
    fun getDuration(): Long {
        return cachedDurationMs
    }

    /**
     * Returns the player ID assigned during initialization.
     * Called from Rust JNI to route frames to the correct per-player queue.
     */
    fun getPlayerId(): Long {
        return playerId
    }

    /**
     * Sets the video surface from native code (NDK ImageReader mode).
     *
     * Called by Rust when using NDK AImageReader for zero-copy with sync fence support.
     *
     * @param surface The Surface from ANativeWindow_toSurface (backed by NDK AImageReader)
     */
    fun setVideoSurfaceFromNative(surface: Surface) {
        Log.d(TAG, "setVideoSurfaceFromNative called - switching to NDK ImageReader mode")
        // Post all mutations to the handler thread to avoid racing with
        // onImageAvailable and setupImageReader
        handler?.post {
            ndkMode = true
            imageReader?.close()
            imageReader = null
            this.surface?.release()
            this.surface = surface
            player?.setVideoSurface(surface)
            Log.i(TAG, "Video surface set from native (NDK ImageReader mode active)")
        } ?: Log.w(TAG, "setVideoSurfaceFromNative called before handler initialized")
    }

    /**
     * Creates or recreates the ImageReader with the correct dimensions.
     *
     * IMPORTANT: ImageReader dimensions MUST match video resolution,
     * otherwise BufferQueue errors will occur.
     */
    private fun setupImageReader(width: Int, height: Int) {
        if (width == videoWidth && height == videoHeight && imageReader != null) {
            return
        }

        // Keep the previous BufferQueue alive until ExoPlayer/MediaCodec has
        // completed its asynchronous setOutputSurface handoff. Closing it here
        // first abandons the queue while the hardware decoder still owns
        // dequeued buffers, which can release the codec before setSurface runs.
        val previousReader = imageReader
        val previousSurface = surface

        Log.i(TAG, "Setting up ImageReader: ${width}x${height}")

        try {
            val newReader = ImageReader.newInstance(
                width,
                height,
                ImageFormat.PRIVATE,
                MAX_IMAGES
            ).apply {
                setOnImageAvailableListener(
                    { reader -> onImageAvailable(reader) },
                    handler
                )
            }

            val newSurface = newReader.surface
            player?.setVideoSurface(newSurface)

            imageReader = newReader
            surface = newSurface
            videoWidth = width
            videoHeight = height

            if (previousReader != null || previousSurface != null) {
                handler?.postDelayed({
                    previousSurface?.release()
                    previousReader?.close()
                    Log.d(TAG, "Retired previous ImageReader after surface handoff")
                }, 1_000L)
            }

            Log.i(TAG, "ImageReader created and attached to player")
        } catch (e: Exception) {
            Log.e(TAG, "Failed to create ImageReader: ${e.message}")
        }
    }

    /**
     * Called when a new decoded frame is available in the ImageReader.
     */
    private fun onImageAvailable(reader: ImageReader) {
        if (isReleased.get()) return
        if (!nativeLibraryLoaded) return

        val image = try {
            reader.acquireLatestImage()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to acquire image: ${e.message}")
            return
        } ?: return

        var hardwareBuffer: HardwareBuffer? = null
        var retainedByNative = false
        try {
            hardwareBuffer = image.hardwareBuffer
            if (hardwareBuffer != null) {
                val fenceFd = -1
                // Image.timestamp is a CLOCK_MONOTONIC capture timestamp (effectively
                // device uptime), not a timestamp in the media timeline. Feeding it to
                // Lumina as a frame PTS makes the displayed position jump by hours and
                // causes the scheduler to drop otherwise valid frames. This callback
                // runs on ExoPlayer's application looper, so currentPosition is safe to
                // query here and tracks the audio/media clock used for presentation.
                val mediaPositionMs = player?.currentPosition
                    ?.let(::normalizedPositionMs)
                    ?: cachedPositionMs.coerceAtLeast(0L)
                cachedPositionMs = mediaPositionMs
                val mediaTimestampNs = mediaTimestampForImage(image.timestamp, mediaPositionMs)

                retainedByNative = nativeSubmitHardwareBuffer(
                    image,
                    hardwareBuffer,
                    mediaTimestampNs,
                    image.width,
                    image.height,
                    playerId,
                    fenceFd
                )

                frameCount.incrementAndGet()
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error processing frame: ${e.message}")
        } finally {
            hardwareBuffer?.close()
            if (!retainedByNative) {
                image.close()
            }
        }
    }

    /**
     * Gets the number of frames submitted to Rust.
     */
    fun getFrameCount(): Int = frameCount.get()

    /**
     * Releases all resources held by this bridge.
     *
     * Safe to call multiple times (idempotent).
     */
    fun release() {
        if (isReleased.getAndSet(true)) {
            return
        }

        Log.i(TAG, "Releasing bridge (submitted ${frameCount.get()} frames, player_id=$playerId)")

        // ExoPlayer must be completely released on its application Looper
        // before that Looper is asked to quit. Posting cleanup and immediately
        // calling quitSafely raced Media3's listener notifications with a dead
        // MessageQueue, especially during rapid source switching.
        val playerHandler = handler
        val thread = handlerThread
        val cleanupComplete = CountDownLatch(1)
        val cleanup = Runnable {
            try {
                playerListener?.let { listener ->
                    player?.removeListener(listener)
                }
                playerListener = null

                // Releasing the old codec is the synchronization boundary for
                // a source switch. The next player must not compete with it for
                // MediaCodec/Surface resources.
                player?.release()
                player = null

                surface?.release()
                surface = null

                imageReader?.close()
                imageReader = null

                // This runs after all earlier ImageReader callbacks on the same
                // Looper, so no old callback can recreate the native queue.
                if (nativeLibraryLoaded && playerId != 0L) {
                    nativeReleasePlayer(playerId)
                }
            } finally {
                cleanupComplete.countDown()

                // Media3 worker threads can deliver tail events after release.
                // Drain them without making the source-switch path join this
                // HandlerThread.
                playerHandler?.postDelayed({
                    thread?.quitSafely()
                    if (handlerThread === thread) {
                        handlerThread = null
                        handler = null
                    }
                }, 1_500L)
            }
        }

        if (playerHandler != null && thread != null) {
            if (Thread.currentThread() === thread) {
                cleanup.run()
            } else if (!playerHandler.post(cleanup)) {
                Log.w(TAG, "Player thread already stopped; releasing remaining resources directly")
                cleanup.run()
            } else if (!cleanupComplete.await(INIT_TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
                Log.w(TAG, "Timed out waiting for old ExoPlayer codec release")
            }
        } else {
            cleanup.run()
        }

        // The codec is gone before returning, but the old Looper drains and
        // exits asynchronously; there is deliberately no thread join here.
    }

    // ========================================================================
    // JNI Native Methods
    // ========================================================================

    private external fun nativeGeneratePlayerId(): Long

    private external fun nativeReleasePlayer(playerId: Long)

    private external fun nativeSubmitHardwareBuffer(
        image: android.media.Image,
        buffer: HardwareBuffer,
        timestampNs: Long,
        width: Int,
        height: Int,
        playerId: Long,
        fenceFd: Int
    ): Boolean

    private external fun nativeOnVideoSizeChanged(nativeHandle: Long, width: Int, height: Int)

    private external fun nativeOnPlaybackStateChanged(nativeHandle: Long, stateValue: Int)

    private external fun nativeOnError(nativeHandle: Long, errorMessage: String)

    private external fun nativeOnDurationChanged(nativeHandle: Long, durationMs: Long)
}
