/**
 * ExoPlayer bridge retaining native Images through GPU consumption.
 * Native frames are the default. CPU-readable YUV output is selected only when
 * producer synchronization or renderer import is unavailable.
 */
package com.luminavideo.bridge

import android.content.Context
import android.graphics.ImageFormat
import android.hardware.HardwareBuffer
import android.media.ImageReader
import android.os.Build
import android.os.Handler
import android.os.HandlerThread
import android.os.Looper
import android.os.SystemClock
import android.util.Log
import android.view.Surface
import androidx.media3.common.MediaItem
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.common.Timeline
import androidx.media3.common.VideoSize
import androidx.media3.exoplayer.ExoPlayer
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger

// Never call Image.planes for opaque/vendor buffers: some Android drivers abort
// in nativeCreatePlanes instead of throwing a catchable Java exception.
internal fun isCpuReadableYuvImage(imageFormat: Int, bufferFormat: Int, usage: Long): Boolean =
    imageFormat == ImageFormat.YUV_420_888 &&
        bufferFormat == HardwareBuffer.YCBCR_420_888 &&
        usage and HardwareBuffer.USAGE_CPU_READ_OFTEN != 0L

/**
 * Bridge between ExoPlayer and lumina-video's Rust rendering.
 *
 * Retains native ImageReader frames through GPU consumption, with explicit
 * system-memory fallback when native synchronization or import is unavailable.
 *
 * Instances are created by [LuminaVideo.createPlayer] — do not construct directly.
 */
class ExoPlayerBridge internal constructor(private val nativeHandle: Long = 0L) {

    companion object {
        private const val TAG = "ExoPlayerBridge"

        /** Maximum number of images to hold in the ImageReader buffer */
        // CorePlayer's five queued frames, GPU/current/import frames, one native
        // mailbox frame, and acquireLatestImage headroom stay bounded together.
        private const val MAX_IMAGES = 12

        /** Timeout for ExoPlayer creation on the HandlerThread */
        private const val INIT_TIMEOUT_SECONDS = 5L

        /** Whether the native library was successfully loaded */
        @Volatile private var nativeLibraryLoaded = false

        init {
            try {
                System.loadLibrary("lumina_video_android")
                nativeLibraryLoaded = true
                Log.i(TAG, "Loaded liblumina_video_android.so")
            } catch (e: UnsatisfiedLinkError) {
                nativeLibraryLoaded = false
                Log.d(TAG, "Standalone JNI library absent; using the host application library")
            }
        }
    }

    // ImageReader for capturing decoded frames
    private var imageReader: ImageReader? = null

    // Surface provided to ExoPlayer for rendering
    private var surface: Surface? = null

    // Dedicated Looper thread for ExoPlayer (ExoPlayer requires a Looper thread)
    private var handlerThread: HandlerThread? = null
    private var handler: Handler? = null
    // Before API 33 Java Image exposes no producer fence. Use the safe last tier.
    private var cpuFallback = Build.VERSION.SDK_INT < 33
    // MediaCodec surface timestamps are release times, not media PTS. Keep a
    // bounded correspondence until ImageReader returns the associated image.
    private val frameTimestamps = FrameTimeline(MAX_IMAGES * 2)
    // Reused only on the player's application looper, including ImageReader callbacks.
    private val framePeriod = Timeline.Period()
    private val liveWindowRecovery = LiveWindowRecovery()

    // Volume before muting (to restore on unmute)
    private var volumeBeforeMute: Float = 1.0f

    // Player reference for lifecycle management
    private var player: ExoPlayer? = null

    // State tracking
    private val isReleased = AtomicBoolean(false)
    // Rust releases its native handle when release() returns. Serialize only
    // metadata/error callbacks with that boundary, never per-frame pixel work.
    private val nativeCallbackLock = Any()

    private inline fun withNativeHandle(callback: (Long) -> Unit) {
        synchronized(nativeCallbackLock) {
            if (!isReleased.get() && nativeHandle != 0L) callback(nativeHandle)
        }
    }
    private val frameCount = AtomicInteger(0)

    // Player listener for cleanup on release
    private var playerListener: Player.Listener? = null

    // Player ID for per-player frame queue routing.
    // Generated by nativeGeneratePlayerId() during init; 0 = not yet assigned.
    private var playerId: Long = 0L

    // Current video dimensions (updated on video size change)
    private var videoWidth = 0
    private var videoHeight = 0

    // True when Surface is provided by native NDK ImageReader (via setVideoSurfaceFromNative)
    private var ndkMode = false

    // Cached position/duration — updated on player thread, read from any thread.
    // ExoPlayer with setLooper() enforces thread access, so we can't call getters directly
    // from Rust's decode thread. These volatile fields provide stale-but-safe reads.
    @Volatile private var cachedPositionMs: Long = 0L
    @Volatile private var cachedDurationMs: Long = -1L

    /**
     * Creates ExoPlayer on a dedicated HandlerThread and sets up ImageReader.
     *
     * This method blocks the calling thread (via CountDownLatch) until ExoPlayer
     * is fully initialized, or until [INIT_TIMEOUT_SECONDS] elapses.
     *
     * Called by [LuminaVideo.createPlayer] from a Rust background thread.
     *
     * @param context Application context for ExoPlayer creation
     * @param builder Optional custom ExoPlayer.Builder. If null, default is used.
     * @return true if ExoPlayer was created successfully, false on timeout or error
     */
    internal fun initializeWithPlayer(context: Context, builder: ExoPlayer.Builder? = null): Boolean {
        if (isReleased.get()) {
            Log.w(TAG, "Cannot initialize - bridge is released")
            return false
        }

        // Generate unique player ID for per-player frame queue isolation
        playerId = try {
            // Embedded hosts already load the JNI implementation under their
            // own library name. Resolve the symbol instead of assuming a name.
            nativeGeneratePlayerId().also { nativeLibraryLoaded = true }
        } catch (error: LinkageError) {
            Log.e(TAG, "Host application has not loaded the Lumina JNI implementation", error)
            return false
        } catch (error: Exception) {
            Log.e(TAG, "Could not allocate a native player queue", error)
            return false
        }
        Log.i(TAG, "Assigned player_id=$playerId")

        // Create dedicated Looper thread for this player instance
        handlerThread = HandlerThread("LuminaVideoPlayer").apply { start() }
        handler = Handler(handlerThread!!.looper)

        val latch = CountDownLatch(1)
        var success = false

        handler!!.post {
            try {
                val exoPlayer = (builder ?: ExoPlayer.Builder(context))
                    .setLooper(handlerThread!!.looper)
                    .build()
                    .apply {
                        setVideoScalingMode(androidx.media3.common.C.VIDEO_SCALING_MODE_SCALE_TO_FIT)
                        setVideoFrameMetadataListener { presentationTimeUs, releaseTimeNs, _, _ ->
                            frameTimestamps.record(presentationTimeUs, releaseTimeNs)
                        }
                    }

                player = exoPlayer
                setupListenersAndSurface(exoPlayer)
                success = true
                Log.i(TAG, "ExoPlayer created on ${Thread.currentThread().name}")
            } catch (e: Exception) {
                Log.e(TAG, "Failed to create ExoPlayer: ${e.message}", e)
            }
            latch.countDown()
        }

        val completed = latch.await(INIT_TIMEOUT_SECONDS, TimeUnit.SECONDS)
        if (!completed || !success) {
            Log.e(TAG, "ExoPlayer creation ${if (!completed) "timed out" else "failed"} after ${INIT_TIMEOUT_SECONDS}s, cleaning up")
            release()
            return false
        }

        return true
    }

    /**
     * Sets up video size listener and initial ImageReader surface on the player.
     *
     * Must be called on the player's Looper thread.
     */
    private fun setupListenersAndSurface(exoPlayer: ExoPlayer) {
        // Listen for video size changes, playback state, and errors
        playerListener = object : Player.Listener {
            override fun onTimelineChanged(timeline: Timeline, reason: Int) {
                // Live playlist refreshes move the window origin used by both
                // currentPosition and the frame timestamp conversion below.
                updateCachedValues()
            }

            override fun onPositionDiscontinuity(
                oldPosition: Player.PositionInfo,
                newPosition: Player.PositionInfo,
                reason: Int
            ) {
                frameTimestamps.reset(frameTimestamps.generation())
                updateCachedValues()
            }

            override fun onVideoSizeChanged(videoSize: VideoSize) {
                Log.d(TAG, "onVideoSizeChanged: ${videoSize.width}x${videoSize.height}")
                if (videoSize.width > 0 && videoSize.height > 0) {
                    // Don't set videoWidth/videoHeight here — setupImageReader checks
                    // them for its early-return guard and updates them itself
                    if (!ndkMode) {
                        setupImageReader(videoSize.width, videoSize.height)
                    }
                    withNativeHandle { nativeOnVideoSizeChanged(it, videoSize.width, videoSize.height) }
                }
            }

            override fun onPlaybackStateChanged(playbackState: Int) {
                if (exoPlayer.playbackState == Player.STATE_READY && liveWindowRecovery.finish()) {
                    Log.i(TAG, "Live-window recovery reached READY")
                }
                updateCachedValues()
                withNativeHandle {
                    nativeOnPlaybackStateChanged(it, exoPlayer.playbackState, frameTimestamps.generation())
                }
            }

            override fun onIsPlayingChanged(isPlaying: Boolean) {
                updateCachedValues()
                withNativeHandle { handle ->
                    val dur = exoPlayer.duration
                    val durationMs = if (dur == androidx.media3.common.C.TIME_UNSET) -1L else dur
                    nativeOnDurationChanged(handle, durationMs)
                }
            }

            override fun onPlayerError(error: PlaybackException) {
                if (error.errorCode == PlaybackException.ERROR_CODE_BEHIND_LIVE_WINDOW &&
                    liveWindowRecovery.start(SystemClock.elapsedRealtime())) {
                    Log.w(TAG, "Behind live window; recovering at the default live position")
                    frameTimestamps.reset(frameTimestamps.generation())
                    // Media3's documented recovery. Keep playWhenReady so a
                    // paused session stays paused while its live window moves.
                    exoPlayer.seekToDefaultPosition()
                    exoPlayer.prepare()
                    updateCachedValues()
                    return
                }
                liveWindowRecovery.finish()
                Log.e(TAG, "ExoPlayer error: ${error.message}", error)
                val message = if (error.errorCode == PlaybackException.ERROR_CODE_BEHIND_LIVE_WINDOW) {
                    "Live-window recovery failed or repeated within 30 seconds"
                } else {
                    error.message ?: "Unknown ExoPlayer error"
                }
                withNativeHandle { nativeOnError(it, message) }
            }
        }
        exoPlayer.addListener(playerListener!!)

        // Periodically update cached position/duration on the player thread
        // so Rust can read them from any thread via volatile fields
        startPositionUpdater()

        // Create initial ImageReader (unless NDK mode is active)
        if (!ndkMode && imageReader == null && surface == null) {
            Log.i(TAG, "Creating initial ImageReader with default 1920x1080 size")
            setupImageReader(1920, 1080)
        }
    }

    /**
     * Loads and plays a video from the given URL.
     *
     * Called by Rust code to start video playback. Posts to the player's
     * HandlerThread to satisfy ExoPlayer's threading requirements.
     */
    fun play(url: String) {
        handler?.post {
            val p = player
            if (p == null) {
                Log.w(TAG, "play() called but player not initialized")
                return@post
            }
            Log.d(TAG, "play($url)")
            liveWindowRecovery.reset()
            val mediaItem = MediaItem.fromUri(url)
            p.setMediaItem(mediaItem)
            p.prepare()
            p.play()
        } ?: Log.w(TAG, "play() called before initializeWithPlayer()")
    }

    /**
     * Pauses video playback.
     */
    fun pause() {
        handler?.post { player?.pause() }
    }

    /**
     * Resumes video playback.
     */
    fun resume() {
        handler?.post { player?.play() }
    }

    /**
     * Seeks to the specified position.
     *
     * @param positionMs Position in milliseconds
     */
    fun seek(positionMs: Long, generation: Long) {
        handler?.post {
            frameTimestamps.reset(generation)
            player?.seekTo(positionMs)
            updateCachedValues()
        }
    }

    /**
     * Sets the playback volume.
     *
     * @param volume Volume level (0.0 to 1.0)
     */
    fun setVolume(volume: Float) {
        handler?.post { player?.let { it.volume = volume.coerceIn(0f, 1f) } }
    }

    /**
     * Sets the muted state.
     *
     * @param muted True to mute, false to unmute
     */
    fun setMuted(muted: Boolean) {
        handler?.post {
            player?.let { p ->
                if (muted) {
                    volumeBeforeMute = p.volume
                    p.volume = 0f
                } else {
                    p.volume = volumeBeforeMute
                }
            }
        }
    }

    /**
     * Updates cached position/duration from the player.
     * Must be called on the player's Looper thread.
     */
    private fun updateCachedValues() {
        player?.let { p ->
            cachedPositionMs = p.currentPosition
            val dur = p.duration
            cachedDurationMs = if (dur == androidx.media3.common.C.TIME_UNSET) -1L else dur
        }
    }

    /**
     * Starts a periodic Runnable on the handler thread to update cached position.
     * Runs every 16ms while the player is alive.
     */
    private fun startPositionUpdater() {
        val updater = object : Runnable {
            override fun run() {
                if (!isReleased.get()) {
                    updateCachedValues()
                    if (liveWindowRecovery.hasTimedOut(SystemClock.elapsedRealtime())) {
                        liveWindowRecovery.finish()
                        player?.stop()
                        Log.e(TAG, "Live-window recovery timed out after 10 seconds")
                        withNativeHandle { nativeOnError(it, "Live-window recovery timed out after 10 seconds") }
                    }
                    handler?.postDelayed(this, 16)
                }
            }
        }
        handler?.postDelayed(updater, 16)
    }

    /**
     * Gets the current playback position in milliseconds.
     *
     * Returns a cached value updated every ~16ms on the player thread.
     * Safe to call from any thread (Rust decode thread, main thread, etc.).
     *
     * @return Current position in ms, or 0 if not playing
     */
    fun getCurrentPosition(): Long {
        return cachedPositionMs
    }

    /**
     * Gets the total duration of the video in milliseconds.
     *
     * Returns a cached value updated on playback state changes and periodically.
     * Safe to call from any thread.
     *
     * @return Duration in ms, or -1 if unknown
     */
    fun getDuration(): Long {
        return cachedDurationMs
    }

    /**
     * Returns the player ID assigned during initialization.
     * Called from Rust JNI to route frames to the correct per-player queue.
     */
    fun getPlayerId(): Long {
        return playerId
    }

    /**
     * Sets the video surface from native code (NDK ImageReader mode).
     *
     * Called by Rust when using NDK AImageReader for zero-copy with sync fence support.
     *
     * @param surface The Surface from ANativeWindow_toSurface (backed by NDK AImageReader)
     */
    fun setVideoSurfaceFromNative(surface: Surface) {
        val posted = handler?.post {
            if (isReleased.get()) {
                surface.release()
                return@post
            }
            val previousReader = imageReader
            val previousSurface = this.surface
            try {
                player?.setVideoSurface(surface)
                ndkMode = true
                imageReader = null
                this.surface = surface
                previousSurface?.release()
                previousReader?.close()
            } catch (error: Exception) {
                surface.release()
                withNativeHandle { nativeOnError(it, "Native surface handoff failed: ${error.message}") }
            }
        } == true
        if (!posted) surface.release()
    }

    /**
     * Creates or recreates the ImageReader with the correct dimensions.
     *
     * IMPORTANT: ImageReader dimensions MUST match video resolution,
     * otherwise BufferQueue errors will occur.
     */
    private fun setupImageReader(width: Int, height: Int, force: Boolean = false) {
        if (!force && width == videoWidth && height == videoHeight && imageReader != null) {
            return
        }

        if (isReleased.get()) return
        // setVideoSurface waits for the codec surface handoff. Keep the old
        // BufferQueue alive until it has stopped being the producer target.
        val previousReader = imageReader
        val previousSurface = surface
        var pendingReader: ImageReader? = null
        var pendingSurface: Surface? = null

        Log.i(TAG, "Setting up ImageReader: ${width}x${height}")

        try {
            val newReader = ImageReader.newInstance(
                width,
                height,
                if (cpuFallback) ImageFormat.YUV_420_888 else ImageFormat.PRIVATE,
                MAX_IMAGES
            ).also { pendingReader = it }.apply {
                setOnImageAvailableListener(
                    { reader -> onImageAvailable(reader) },
                    handler
                )
            }

            val newSurface = newReader.surface
            pendingSurface = newSurface
            player?.setVideoSurface(newSurface)

            imageReader = newReader
            surface = newSurface
            videoWidth = width
            videoHeight = height
            pendingReader = null
            pendingSurface = null
            previousSurface?.release()
            previousReader?.close()

            Log.i(TAG, "ImageReader created and attached to player")
        } catch (e: Exception) {
            pendingSurface?.release()
            pendingReader?.close()
            Log.e(TAG, "Failed to create ImageReader: ${e.message}")
            if (!cpuFallback) {
                // Preserve the requested dimensions for the one safe fallback.
                videoWidth = width
                videoHeight = height
                enableCpuFallback()
            } else {
                withNativeHandle { nativeOnError(it, "Video output unavailable: ${e.message}") }
            }
        }
    }

    /** Called from the Rust decoder worker after native renderer import failed. */
    fun enableCpuFallback() {
        handler?.post {
            if (!isReleased.get() && !cpuFallback) {
                cpuFallback = true
                Log.w(TAG, "Native video import unavailable; selecting system-memory upload")
                if (videoWidth > 0 && videoHeight > 0) {
                    // Surface replacement alone can carry the codec's PRIVATE
                    // allocations into a YUV reader. Release/reconfigure the
                    // codec while preserving the existing playback position/state.
                    val fallbackPlayer = player
                    val position = fallbackPlayer?.currentPosition
                    fallbackPlayer?.stop()
                    frameTimestamps.reset(frameTimestamps.generation())
                    setupImageReader(videoWidth, videoHeight, force = true)
                    if (position != null) fallbackPlayer.seekTo(position)
                    fallbackPlayer?.prepare()
                }
            }
        }
    }

    /**
     * Called when a new decoded frame is available in the ImageReader.
     */
    private fun onImageAvailable(reader: ImageReader) {
        if (isReleased.get()) return
        if (!nativeLibraryLoaded) return
        // Listener messages from a replaced reader can already be queued.
        // They must not be interpreted using the new output mode.
        if (reader !== imageReader) return

        val image = try {
            reader.acquireLatestImage()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to acquire image: ${e.message}")
            return
        } ?: return

        var retained = false
        var hardwareBuffer: HardwareBuffer? = null
        try {
            val p = player ?: return
            val timeline = p.currentTimeline
            val periodIndex = p.currentPeriodIndex
            if (periodIndex !in 0 until timeline.periodCount) return
            // Matches Media3 ExoPlayerImpl.getCurrentPositionUsInternal:
            // content period time + positionInWindowUs; ads use their own clock.
            // Do not read Player from the codec-thread metadata callback.
            val periodOffsetUs = if (p.isPlayingAd) 0L else
                timeline.getPeriod(periodIndex, framePeriod).positionInWindowUs
            if (periodOffsetUs == androidx.media3.common.C.TIME_UNSET) return
            val stamp = frameTimestamps.take(image.timestamp, periodOffsetUs)
                ?: return // Drop unmatched/stale output instead of publishing a wall-clock PTS.
            val timestampNs = Math.multiplyExact(stamp.presentationTimeUs, 1000L)
            if (!cpuFallback && Build.VERSION.SDK_INT >= 33) {
                // No CPU pixels are copied. The bounded acquire wait runs on
                // this player's handler thread, never on the UI/render thread.
                image.fence.use { fence ->
                    check(!fence.isValid || fence.await(java.time.Duration.ofSeconds(2))) {
                        "Video producer fence timed out"
                    }
                }
                hardwareBuffer = image.hardwareBuffer
                val buffer = checkNotNull(hardwareBuffer) { "Image has no HardwareBuffer" }
                retained = nativeSubmitImageFrame(image, buffer, timestampNs,
                    image.width, image.height, playerId, stamp.generation)
                check(retained) { "Failed to retain native video Image" }
            } else {
                // Validate the actual allocation before touching planes; Image's
                // logical format alone can conceal an opaque vendor allocation.
                check(image.format == ImageFormat.YUV_420_888) { "CPU image is not YUV" }
                if (Build.VERSION.SDK_INT >= 28) {
                    hardwareBuffer = image.hardwareBuffer
                    val buffer = checkNotNull(hardwareBuffer) { "CPU image has no HardwareBuffer" }
                    check(isCpuReadableYuvImage(image.format, buffer.format, buffer.usage)) {
                        "CPU output is not readable YUV: image=${image.format}, " +
                            "buffer=${buffer.format}, usage=${buffer.usage}"
                    }
                }
                // API 26/27 start with a YUV-configured codec and never transition
                // from PRIVATE output; Image.getHardwareBuffer begins at API 28.
                // Last-resort snapshot before Image.close permits decoder reuse.
                val planes = image.planes
                check(planes.size == 3) { "Expected CPU-readable YUV_420_888 output" }
                check(nativeSubmitCpuFrame(
                    planes[0].buffer.slice(), planes[0].rowStride, planes[0].pixelStride,
                    planes[1].buffer.slice(), planes[1].rowStride, planes[1].pixelStride,
                    planes[2].buffer.slice(), planes[2].rowStride, planes[2].pixelStride,
                    timestampNs,
                    image.width,
                    image.height,
                    playerId,
                    stamp.generation
                )) { "Failed to snapshot video image" }
            }
            frameCount.incrementAndGet()
        } catch (e: Exception) {
            Log.e(TAG, "Error processing frame: ${e.message}")
            if (!cpuFallback) {
                enableCpuFallback()
            } else {
                withNativeHandle { nativeOnError(it, "CPU video frame failed: ${e.message}") }
            }
        } finally {
            hardwareBuffer?.close()
            if (!retained) image.close()
        }
    }

    /**
     * Gets the number of frames submitted to Rust.
     */
    fun getFrameCount(): Int = frameCount.get()

    /**
     * Releases all resources held by this bridge.
     *
     * Safe to call multiple times (idempotent).
     */
    fun release() {
        synchronized(nativeCallbackLock) {
            if (!isReleased.compareAndSet(false, true)) return
        }
        LuminaVideo.onBridgeReleased(this)
        val playerHandler = handler
        val thread = handlerThread
        val cleanupComplete = CountDownLatch(1)
        val cleanup = Runnable {
            try {
                playerListener?.let { player?.removeListener(it) }
                playerListener = null
                player?.release()
            } catch (error: Exception) {
                Log.e(TAG, "Player release failed", error)
            } finally {
                player = null
                surface?.release()
                surface = null
                imageReader?.close()
                imageReader = null
                if (nativeLibraryLoaded && playerId != 0L) nativeReleasePlayer(playerId)
                handler = null
                handlerThread = null
                cleanupComplete.countDown()
                // Allow Media3's already-dispatched tail notifications to drain.
                if (playerHandler?.postDelayed({ thread?.quitSafely() }, 1_500L) != true) {
                    thread?.quitSafely()
                }
            }
        }
        if (playerHandler == null || Looper.myLooper() === playerHandler.looper) {
            cleanup.run()
        } else if (!playerHandler.post(cleanup)) {
            cleanup.run()
        } else if (Looper.myLooper() !== Looper.getMainLooper()) {
            // Source switches on the decode worker wait for codec release;
            // Activity destruction never blocks the UI or joins its own Looper.
            try {
                if (!cleanupComplete.await(INIT_TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
                    Log.w(TAG, "Timed out waiting for old codec release")
                }
            } catch (_: InterruptedException) {
                Thread.currentThread().interrupt()
            }
        }
    }

    // ========================================================================
    // JNI Native Methods
    // ========================================================================

    private external fun nativeGeneratePlayerId(): Long

    private external fun nativeReleasePlayer(playerId: Long)

    private external fun nativeSubmitImageFrame(
        image: android.media.Image, buffer: HardwareBuffer,
        timestampNs: Long, width: Int, height: Int, playerId: Long, generation: Long
    ): Boolean

    private external fun nativeSubmitCpuFrame(
        y: java.nio.ByteBuffer, yRow: Int, yPixel: Int,
        u: java.nio.ByteBuffer, uRow: Int, uPixel: Int,
        v: java.nio.ByteBuffer, vRow: Int, vPixel: Int,
        timestampNs: Long, width: Int, height: Int, playerId: Long, generation: Long
    ): Boolean

    private external fun nativeOnVideoSizeChanged(nativeHandle: Long, width: Int, height: Int)

    private external fun nativeOnPlaybackStateChanged(nativeHandle: Long, stateValue: Int, generation: Long)

    private external fun nativeOnError(nativeHandle: Long, errorMessage: String)

    private external fun nativeOnDurationChanged(nativeHandle: Long, durationMs: Long)
}
