name: Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Check links in Markdown files
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --exclude-loopback
            --exclude "^https://test-videos\\.co\\.uk"
            --exclude "^https://example\\.com"
            --exclude "vendor-gstreamer-.*gstreamer-vendor-linux"
            --exclude "moqs?:/"
            --exclude "rtmp://"
            --exclude "^https://api-core\\.zap\\.stream"
            --exclude "^https://cdn\\.moq\\.dev"
            --exclude "^https://commondatastorage\\.googleapis\\.com"
            '*.md'
            'crates/**/*.md'
            'crates/**/*.rs'
          fail: true
